version: '3.8'
services:
  ros:
    build: 
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64
    command: tail -f /dev/null
    environment:
      - DISPLAY=host.docker.internal:0
      # - LIBGL_ALWAYS_SOFTWARE=1
      # - LIBGL_ALWAYS_INDIRECT=1
      # - QT_X11_NO_MITSHM=1
    volumes:
      - ./ros_workspace:/root/dev_ws  # Maps your local workspace directory to the container's workspace
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    networks:
      - ros_network

networks:
  ros_network:
    driver: bridge
